[build-system]
requires = [
    "setuptools >= 59.0.0",
    "setuptools_scm[toml] >= 6.2",
    "wheel >= 0.37.0",
]
build-backend = 'setuptools.build_meta'

[tool.black]
line-length = 99

[tool.setuptools_scm]
write_to = "src/tox_gh_matrix/version.py"
